services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5469:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chefs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: britoludopadata
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "6969:8080"
volumes:
  postgres_data:
networks:
  backend:
    driver: bridge
